name: Minewar-Utils
version: 1.0.1
description: "Essential server utilities, chat management, and quality-of-life enhancements"
main: com.jxsh.misc.JxshMisc
api-version: 1.20
authors: [Jxsh]
softdepend: [LuckPerms, ProtocolLib, Velocitab, WorldEdit, FastAsyncWorldEdit, AxiomPaper]
commands:
  minewarutils:
    description: Main command for Minewar-Utils
  minewarutils:
    description: Main command for Minewar-Utils
    usage: /minewarutils <reload|sneak|world>


