name: Minewar-Utils
version: 1.0.1
description: "Essential server utilities, chat management, and quality-of-life enhancements"
main: com.jxsh.misc.JxshMisc
api-version: 1.20
authors: [Jxsh]
softdepend: [LuckPerms, ProtocolLib, Velocitab, WorldEdit, FastAsyncWorldEdit, AxiomPaper]
commands:
  minewarutils:
    description: Main command for Minewar-Utils
  minewarutils:
    description: Main command for Minewar-Utils
    usage: /minewarutils <reload|sneak|world>

permissions:
  minewar.admin:
    description: Allows administrative tasks for the plugin
    default: false
  minewar.admin.reload:
    description: Allows reloading the plugin configuration
    default: false
  minewar.admin.sneak:
    description: Allows toggling the sneak feature for users
    default: false
  minewar.mutechat.toggle:
    description: Allows toggling global chat mute
    default: false
  minewar.mutechat.bypass:
    description: Allows speaking when chat is muted
    default: OP
  minewar.slowchat.set:
    description: Allows setting global chat slow mode
    default: false
  minewar.slowchat.bypass:
    description: Allows bypassing slow chat cooldown
    default: OP
  minewar.clearchat:
    description: Allows clearing global chat
    default: false
  minewar.clearchat.bypass:
    description: Allows bypassing chat clear
    default: OP
  minewar.mentions:
    description: Allows mentioning other players in chat
    default: true
  minewar.mentiontoggle:
    description: Allows toggling mention notifications
    default: true
  
  # New Permissions
  minewar.top:
    default: false
  minewar.bottom:
    default: false
  minewar.heal: 
    default: false
  minewar.eat:   
    default: false
  minewar.fly:   
    default: false
  minewar.flyspeed:   
    default: false
  minewar.gamemode:   
    default: false
  minewar.gamemode.survival:
    default: false
  minewar.gamemode.creative:    
    default: false
  minewar.gamemode.adventure:
    default: false
  minewar.gamemode.spectator:
    default: false
  minewar.inventorysee:
    default: false
  minewar.clearinventory:   
    default: false
  minewar.give:   
    default: false
  minewar.head:    
    default: false
  minewar.setspawn:  
    default: false
  minewar.spawn:
    default: true
  minewar.buildmode:  
    default: false
  minewar.buildmode.admin:   
    default: false
  minewar.buildmode.reset:  
    default: false
  minewar.buildmode.bypass:
    default: false
  minewar.warp:
    default: false
  minewar.setwarp:
    default: false
  minewar.warps:
    default: false
  minewar.itemname:
    default: false
  minewar.lore:
    default: false
  minewar.forcefield:
    default: false
